import { ActivityCategory } from '../types';
import { DestinationCategory } from './profiles';

export interface ActivityTemplate {
  id: string; // unique stable ID for deduplication
  name: string;
  location: string;
  durationMinutes: number;
  priceMin: number; // INR per person
  priceMax: number;
  category: ActivityCategory;
  description: string;
  bookingRequired?: boolean;
  groupFriendly?: boolean;
  budgetFriendly?: boolean;
  premium?: boolean;
  themes?: string[]; // which day themes this activity suits
  lat?: number;
  lon?: number;
}

// Activity banks per destination category
// Each slot must have at least 12 distinct activities to avoid repetition on 7-day trips
export const ACTIVITY_BANK: Record<DestinationCategory, Record<string, ActivityTemplate[]>> = {
  beach: {
    morning: [
      { id: 'bm01', name: 'Sunrise Beach Walk', location: 'Main Beach', durationMinutes: 60, priceMin: 0, priceMax: 0, category: 'nature', description: 'Stroll along the shoreline as the sun rises, watch fishermen bring in the morning catch.', budgetFriendly: true, themes: ['arrival','relax'] },
      { id: 'bm02', name: 'Kayaking & Snorkeling', location: 'Blue Lagoon', durationMinutes: 120, priceMin: 800, priceMax: 1400, category: 'nature', description: 'Explore coral reefs and vivid marine life with a guided kayak and snorkel session.', bookingRequired: true, groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'bm03', name: 'Yoga by the Sea', location: 'Beachfront Shack', durationMinutes: 75, priceMin: 300, priceMax: 600, category: 'rest', description: 'Begin your day with a rejuvenating yoga class facing the ocean.', budgetFriendly: true, themes: ['relax','arrival'] },
      { id: 'bm04', name: 'Dolphin Watching Boat Ride', location: "Fisherman's Wharf", durationMinutes: 90, priceMin: 700, priceMax: 1200, category: 'nature', description: 'Spot playful dolphins in their natural habitat on a guided boat excursion.', bookingRequired: true, groupFriendly: true, themes: ['nature','explore'] },
      { id: 'bm05', name: 'Parasailing over the Coast', location: 'Calangute Beach', durationMinutes: 60, priceMin: 1200, priceMax: 2000, category: 'nature', description: 'Soar high above the coast strapped to a parachute for breathtaking aerial views.', bookingRequired: true, groupFriendly: true, themes: ['adventure'] },
      { id: 'bm06', name: 'Dudhsagar Falls Day Trip', location: 'Dudhsagar Falls', durationMinutes: 300, priceMin: 1000, priceMax: 1800, category: 'nature', description: "Trek or jeep-safari to India's most majestic waterfall deep in the Western Ghats.", bookingRequired: true, groupFriendly: true, themes: ['nature','adventure'] },
      { id: 'bm07', name: 'Stand-Up Paddleboarding', location: 'Candolim Beach', durationMinutes: 90, priceMin: 600, priceMax: 1100, category: 'nature', description: 'Balance on a paddleboard and glide over calm morning waters with an instructor.', bookingRequired: true, themes: ['adventure','explore'] },
      { id: 'bm08', name: 'Old Goa Churches Heritage Walk', location: 'Old Goa', durationMinutes: 150, priceMin: 100, priceMax: 300, category: 'culture', description: "Visit the Basilica of Bom Jesus and Se Cathedral - UNESCO heritage sites from Portugal's colonial era.", budgetFriendly: true, groupFriendly: true, themes: ['culture'] },
      { id: 'bm09', name: 'Fontainhas Latin Quarter Walk', location: 'Fontainhas, Panjim', durationMinutes: 90, priceMin: 0, priceMax: 100, category: 'culture', description: "Wander Goa's preserved Portuguese neighbourhood with brightly painted houses and hidden cafes.", budgetFriendly: true, themes: ['culture','relax'] },
      { id: 'bm10', name: 'Fishermen Village Wake-Up Tour', location: "Fishermen's Village", durationMinutes: 75, priceMin: 200, priceMax: 400, category: 'culture', description: "Join local fishermen at dawn, watch the morning auction, and taste the day's freshest catch.", budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'bm11', name: 'Scuba Diving Discovery Session', location: 'Grande Island', durationMinutes: 180, priceMin: 2500, priceMax: 4000, category: 'nature', description: 'Your first dive - certified instructor guides you to vivid reefs teeming with tropical fish.', bookingRequired: true, premium: true, themes: ['adventure','explore'] },
      { id: 'bm12', name: 'Mangrove Kayak Eco-Tour', location: 'Chapora River Mangroves', durationMinutes: 120, priceMin: 700, priceMax: 1300, category: 'nature', description: 'Paddle through quiet mangrove channels spotting kingfishers, crabs, and coastal wildlife.', bookingRequired: true, themes: ['nature','relax'] },
      { id: 'bm13', name: 'Vagator Cliff Sunrise Walk', location: 'Vagator Cliffs', durationMinutes: 60, priceMin: 0, priceMax: 0, category: 'nature', description: 'Climb to the dramatic red laterite cliffs above Vagator Beach for a stunning sunrise.', budgetFriendly: true, themes: ['nature','relax'] },
      { id: 'bm14', name: 'Cooking Class: Goan Cuisine', location: 'Local Home Kitchen', durationMinutes: 150, priceMin: 1200, priceMax: 2000, category: 'food', description: 'Learn to cook vindaloo, sorpotel, and bebinca from a Goan host in their home kitchen.', bookingRequired: true, premium: true, themes: ['food','culture'] },
    ],
    midday: [
      { id: 'bn01', name: 'Seafood Lunch at Beach Shack', location: 'South Beach Shacks', durationMinutes: 75, priceMin: 450, priceMax: 800, category: 'food', description: 'Tuck into fresh grilled fish, prawn curry, and coconut rice at a classic beach shack.', budgetFriendly: true, themes: ['arrival','explore','relax'] },
      { id: 'bn02', name: 'Local Fish Market Tour', location: 'Municipal Fish Market', durationMinutes: 60, priceMin: 100, priceMax: 200, category: 'culture', description: 'Walk through the bustling fish market and learn about daily catches from local fishermen.', budgetFriendly: true, themes: ['culture','food'] },
      { id: 'bn03', name: 'Clifftop Cafe Lunch', location: 'Cliff-top Cafe', durationMinutes: 60, priceMin: 600, priceMax: 1200, category: 'food', description: 'Enjoy wood-fired pizzas and fresh juice at a scenic clifftop restaurant with ocean views.', premium: true, themes: ['relax','explore'] },
      { id: 'bn04', name: 'Panjim Riverside Lunch', location: 'Mandovi Riverside', durationMinutes: 75, priceMin: 400, priceMax: 900, category: 'food', description: "Dine along the Mandovi riverfront with views of the city and Goa's iconic floating casino.", themes: ['culture','explore'] },
      { id: 'bn05', name: 'Street Food Lunch in Panjim', location: 'Panjim Market Area', durationMinutes: 60, priceMin: 150, priceMax: 350, category: 'food', description: "Dive into Goa's street food scene: ros omelette, chourico pav, and freshly squeezed sugarcane.", budgetFriendly: true, themes: ['food','culture'] },
      { id: 'bn06', name: 'Spice Plantation Lunch Experience', location: 'Inland Spice Farm', durationMinutes: 150, priceMin: 700, priceMax: 1200, category: 'culture', description: 'Tour a working spice plantation, then sit down to a traditional Goan lunch on banana leaves.', groupFriendly: true, bookingRequired: true, themes: ['culture','nature'] },
      { id: 'bn07', name: 'Beach Bar Buffet', location: 'Baga Beach Bar', durationMinutes: 90, priceMin: 800, priceMax: 1500, category: 'food', description: 'All-you-can-eat seafood buffet at a Baga beach bar with live acoustic music.', groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'bn08', name: 'Coconut Toddy & Cashew Feni Tasting', location: 'Local Toddy Shop', durationMinutes: 60, priceMin: 200, priceMax: 400, category: 'food', description: "Sample Goa's traditional toddy and cashew feni liquor with fried snacks at an old-school bar.", budgetFriendly: true, themes: ['culture','food'] },
      { id: 'bn09', name: 'Vegan Beach Cafe', location: 'Ashwem Beach', durationMinutes: 60, priceMin: 500, priceMax: 1000, category: 'food', description: 'Bowls, smoothies, and organic salads at a laid-back yoga-cafe on quiet Ashwem Beach.', themes: ['relax'] },
      { id: 'bn10', name: 'Portuguese Heritage Lunch', location: 'Fontainhas Restaurant', durationMinutes: 90, priceMin: 700, priceMax: 1400, category: 'food', description: 'Indulge in Goan-Portuguese fusion: chorizo stew, caldo verde, and sorbet in a heritage home.', premium: true, themes: ['culture'] },
      { id: 'bn11', name: 'Thali at a Local Canteen', location: 'Old Panjim Lane', durationMinutes: 45, priceMin: 120, priceMax: 250, category: 'food', description: "Eat like a local - a full fish thali for under 200 at a no-frills workers canteen.", budgetFriendly: true, themes: ['food','arrival'] },
      { id: 'bn12', name: 'Boatside Crab Lunch', location: 'Mandovi Estuary', durationMinutes: 90, priceMin: 900, priceMax: 1800, category: 'food', description: 'Fresh crabs cooked in butter-garlic or recheado masala on a river-moored boat restaurant.', premium: true, bookingRequired: true, themes: ['food','nature'] },
    ],
    afternoon: [
      { id: 'ba01', name: 'Jet Ski & Water Sports', location: 'Water Sports Center', durationMinutes: 90, priceMin: 1200, priceMax: 2200, category: 'nature', description: 'Race across the waves on a jet ski or try banana-boat rides over the coast.', bookingRequired: true, groupFriendly: true, themes: ['adventure'] },
      { id: 'ba02', name: 'Secret Cove Exploration', location: 'North Headland', durationMinutes: 120, priceMin: 0, priceMax: 100, category: 'nature', description: 'Trek along the coastal headland path to discover secluded coves and tide pools.', budgetFriendly: true, themes: ['nature','explore'] },
      { id: 'ba03', name: 'Spice Plantation Visit', location: 'Inland Spice Farm', durationMinutes: 120, priceMin: 350, priceMax: 600, category: 'culture', description: 'Tour a working spice plantation, taste local spices, and learn about tropical cultivation.', groupFriendly: true, themes: ['culture','nature'] },
      { id: 'ba04', name: 'Beginner Surfing Lesson', location: 'Surf School, Baga Beach', durationMinutes: 120, priceMin: 900, priceMax: 1600, category: 'nature', description: 'Take a beginner surfing lesson with certified instructors on gentle rolling waves.', bookingRequired: true, themes: ['adventure'] },
      { id: 'ba05', name: 'Chapora Fort & Vagator Views', location: 'Chapora Fort', durationMinutes: 90, priceMin: 0, priceMax: 50, category: 'culture', description: "Climb the iconic fort, enjoy sweeping views over Vagator and Chapora river.", budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'ba06', name: 'Anjuna Flea Market', location: 'Anjuna Beach', durationMinutes: 150, priceMin: 200, priceMax: 600, category: 'shopping', description: "Browse hundreds of stalls at Goa's legendary Wednesday flea market: clothes, jewellery, and art.", groupFriendly: true, themes: ['culture','shopping'] },
      { id: 'ba07', name: 'Cola Beach Hike', location: 'Cola Beach', durationMinutes: 120, priceMin: 0, priceMax: 100, category: 'nature', description: "Trek through jungle to Goa's most secluded beach - a freshwater lagoon meets the sea.", budgetFriendly: true, themes: ['nature','adventure'] },
      { id: 'ba08', name: 'Palolem Beach Kayaking', location: 'Palolem Beach', durationMinutes: 90, priceMin: 500, priceMax: 900, category: 'nature', description: 'Paddle a kayak around the headland of Palolem bay as the sky turns gold.', bookingRequired: true, themes: ['nature','relax'] },
      { id: 'ba09', name: 'Goa Village Heritage Walk', location: 'Old Goa Villages', durationMinutes: 90, priceMin: 0, priceMax: 100, category: 'culture', description: 'Wander rice paddies, old Hindu temples, and colonial-era chapels on a quiet rural afternoon.', budgetFriendly: true, themes: ['culture'] },
      { id: 'ba10', name: 'Backwater Ferry to Divar Island', location: 'Mandovi River Ferry', durationMinutes: 60, priceMin: 10, priceMax: 50, category: 'nature', description: "Ride the public ferry to Divar Island - a forgotten gem of old Goa.", budgetFriendly: true, themes: ['culture','relax'] },
      { id: 'ba11', name: 'Pottery Workshop in Bicholim', location: 'Bicholim Village', durationMinutes: 120, priceMin: 400, priceMax: 800, category: 'culture', description: "Try wheel-thrown pottery at a village studio and take home a piece of Goa's craft heritage.", bookingRequired: true, themes: ['culture','food'] },
      { id: 'ba12', name: 'Ashwem & Mandrem Beach Wander', location: 'Ashwem-Mandrem', durationMinutes: 90, priceMin: 0, priceMax: 100, category: 'nature', description: "Stroll between Goa's quietest northern beaches, stopping at hammock cafes and tide pools.", budgetFriendly: true, themes: ['relax'] },
      { id: 'ba13', name: 'Glass-Bottom Boat Tour', location: 'South Goa', durationMinutes: 90, priceMin: 600, priceMax: 1200, category: 'nature', description: 'Glide over shallow reefs in a glass-bottom boat watching colourful fish without getting wet.', bookingRequired: true, groupFriendly: true, themes: ['nature','explore'] },
    ],
    evening: [
      { id: 'be01', name: 'Sunset at Clifftop Bar', location: 'Clifftop Lounge', durationMinutes: 90, priceMin: 400, priceMax: 900, category: 'nightlife', description: 'Watch the sun dip into the sea with cocktails at a famous clifftop bar.', premium: true, themes: ['arrival','relax','departure'] },
      { id: 'be02', name: 'Beach Night Market', location: 'Saturday Night Bazaar', durationMinutes: 120, priceMin: 300, priceMax: 700, category: 'shopping', description: 'Browse vibrant night market stalls for local crafts, clothes, and street food.', groupFriendly: true, budgetFriendly: true, themes: ['culture','shopping'] },
      { id: 'be03', name: 'Bonfire & Acoustic Night', location: 'Beach Bonfire Spot', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'nightlife', description: 'Join a community bonfire with live acoustic music and local food on the beach.', groupFriendly: true, themes: ['relax','explore'] },
      { id: 'be04', name: 'Seafood Dinner under Stars', location: 'Seaside Restaurant', durationMinutes: 90, priceMin: 800, priceMax: 1800, category: 'food', description: 'Fine dining with lobster, crab, and fresh catch under a canopy of stars.', premium: true, bookingRequired: true, themes: ['explore','adventure'] },
      { id: 'be05', name: "Tito's Lane Nightlife", location: "Tito's Lane, Baga", durationMinutes: 180, priceMin: 600, priceMax: 1500, category: 'nightlife', description: "Experience Goa's legendary nightlife strip with beach clubs, DJs, and bar-hopping.", groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'be06', name: 'Sundown Cruise on Mandovi', location: 'Panaji Jetty', durationMinutes: 90, priceMin: 500, priceMax: 1000, category: 'nature', description: 'Cruise along the Mandovi river at sunset with Konkani music and local snacks.', groupFriendly: true, bookingRequired: true, themes: ['culture','relax','arrival'] },
      { id: 'be07', name: 'Cashew Feni & Tapas Evening', location: 'Panjim Bar', durationMinutes: 90, priceMin: 400, priceMax: 900, category: 'food', description: "Discover the flavours of cashew feni at a cosy bar with Goan tapas.", themes: ['food','culture'] },
      { id: 'be08', name: 'Anjuna Psytrance Night', location: 'Anjuna Club', durationMinutes: 180, priceMin: 500, priceMax: 1200, category: 'nightlife', description: "Dance the night away at Anjuna's legendary trance parties that made Goa famous.", groupFriendly: true, themes: ['adventure'] },
      { id: 'be09', name: 'Palolem Silent Disco', location: 'Palolem Beach', durationMinutes: 150, priceMin: 400, priceMax: 700, category: 'nightlife', description: "Join Palolem's famous headphone-disco on the beach - pick your own channel and dance.", groupFriendly: true, themes: ['adventure','relax'] },
      { id: 'be10', name: 'Heritage Dinner at Restored Villa', location: 'Altinho, Panaji', durationMinutes: 120, priceMin: 1200, priceMax: 2500, category: 'food', description: 'Four-course Goan-Portuguese dinner in a restored 200-year-old villa by candlelight.', premium: true, bookingRequired: true, themes: ['culture','food'] },
      { id: 'be11', name: 'Beachside Bonfire BBQ', location: 'Quiet North Beach', durationMinutes: 120, priceMin: 600, priceMax: 1000, category: 'food', description: 'Private BBQ setup on the beach - grill prawns, fish, and corn while watching the surf.', groupFriendly: true, bookingRequired: true, themes: ['explore','nature'] },
      { id: 'be12', name: 'Stargazing at Chorao Island', location: 'Chorao Island', durationMinutes: 90, priceMin: 100, priceMax: 300, category: 'nature', description: "Ferry to Chorao's wildlife sanctuary after dark for remarkable stargazing and mangrove sounds.", budgetFriendly: true, themes: ['nature','relax'] },
    ],
  },

  mountain: {
    morning: [
      { id: 'mm01', name: 'Alpine Trek to Ridgeline', location: 'Trailhead, Forest Base', durationMinutes: 180, priceMin: 200, priceMax: 500, category: 'nature', description: 'Trek through pine and deodar forests to a spectacular ridgeline with valley views.', budgetFriendly: true, groupFriendly: true, themes: ['explore','adventure','nature'] },
      { id: 'mm02', name: 'Guided River Crossing', location: 'Valley River', durationMinutes: 150, priceMin: 400, priceMax: 900, category: 'nature', description: 'Cross glacial streams with an experienced local guide, spotting alpine wildflowers.', bookingRequired: true, themes: ['adventure','nature'] },
      { id: 'mm03', name: 'Mountain Bike Descent', location: 'Upper Village Road', durationMinutes: 120, priceMin: 800, priceMax: 1500, category: 'nature', description: 'Ride rented mountain bikes down scenic forest trails with panoramic views.', bookingRequired: true, themes: ['adventure'] },
      { id: 'mm04', name: 'Sunrise at Rohtang Pass', location: 'Rohtang Pass', durationMinutes: 240, priceMin: 800, priceMax: 1500, category: 'nature', description: 'An early-morning drive to the high-altitude pass for snow, glaciers, and Himalayan vistas.', bookingRequired: true, groupFriendly: true, themes: ['explore','adventure'] },
      { id: 'mm05', name: 'Wildlife Track Walk', location: 'Upper Forest Zone', durationMinutes: 180, priceMin: 500, priceMax: 1200, category: 'nature', description: 'Walk with a wildlife tracker in the high-altitude forest searching for big cat signs.', bookingRequired: true, premium: true, themes: ['nature','adventure'] },
      { id: 'mm06', name: 'Hampta Pass Acclimatisation Hike', location: 'Hampta Valley', durationMinutes: 210, priceMin: 600, priceMax: 1200, category: 'nature', description: 'A gorgeous mid-altitude hike through alpine meadows to a dramatic mountain pass.', bookingRequired: true, themes: ['adventure','explore'] },
      { id: 'mm07', name: 'Naggar Castle & Art Gallery', location: 'Naggar', durationMinutes: 120, priceMin: 100, priceMax: 300, category: 'culture', description: "Visit the 16th-century castle and the home-gallery of the famous painter Roerich.", budgetFriendly: true, themes: ['culture'] },
      { id: 'mm08', name: 'Hadimba Temple Forest Trail', location: 'Old Manali', durationMinutes: 90, priceMin: 0, priceMax: 50, category: 'culture', description: 'Explore the Hadimba Devi temple complex through ancient deodar forest.', budgetFriendly: true, themes: ['culture','arrival'] },
      { id: 'mm09', name: 'Solang Valley Snow Activities', location: 'Solang Valley', durationMinutes: 180, priceMin: 600, priceMax: 1400, category: 'nature', description: 'Zorbing, snowboarding, and skiing at the snow-sports valley near Manali.', bookingRequired: true, groupFriendly: true, themes: ['adventure'] },
      { id: 'mm10', name: 'Himalayan Birdwatching Walk', location: 'High-altitude Forest', durationMinutes: 150, priceMin: 400, priceMax: 800, category: 'nature', description: 'Spot Himalayan monal, snow partridge, and griffon vultures with a naturalist guide.', bookingRequired: true, themes: ['nature'] },
      { id: 'mm11', name: 'Manali Bazaar Morning Walk', location: 'Mall Road & Bazaar', durationMinutes: 75, priceMin: 0, priceMax: 100, category: 'shopping', description: 'Explore wool shops, dry-fruit stalls, and local cafes before the tourist crowds arrive.', budgetFriendly: true, themes: ['arrival','culture'] },
      { id: 'mm12', name: 'Whitewater Rafting Beas River', location: 'Beas River', durationMinutes: 180, priceMin: 700, priceMax: 1400, category: 'nature', description: 'Paddle Grade 3-4 rapids through a dramatic gorge on the Beas with certified guides.', bookingRequired: true, groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'mm13', name: 'Kullu Shawl Weaving Visit', location: 'Kullu Village', durationMinutes: 120, priceMin: 200, priceMax: 400, category: 'culture', description: 'Watch master weavers at work on traditional Kullu handloom looms and buy directly.', budgetFriendly: true, themes: ['culture'] },
    ],
    midday: [
      { id: 'mn01', name: 'Riverside Dhaba Lunch', location: 'Riverside Dhaba', durationMinutes: 60, priceMin: 250, priceMax: 500, category: 'food', description: 'Savour dal makhani, rajma chawal, and freshly made rotis at a charming mountain dhaba.', budgetFriendly: true, themes: ['arrival','explore'] },
      { id: 'mn02', name: 'Viewpoint Picnic Lunch', location: 'Panorama Point', durationMinutes: 90, priceMin: 150, priceMax: 350, category: 'food', description: 'Pack a simple lunch and dine at a high-altitude viewpoint above the clouds.', budgetFriendly: true, themes: ['nature','adventure'] },
      { id: 'mn03', name: 'Mountain Cafe & Local Brew', location: 'Village Cafe', durationMinutes: 60, priceMin: 400, priceMax: 700, category: 'food', description: 'Enjoy freshly brewed local apple cider and traditional himachali snacks at a cosy cafe.', premium: true, themes: ['relax','food'] },
      { id: 'mn04', name: 'Trout Fish Lunch at Farm', location: 'Trout Fish Farm', durationMinutes: 90, priceMin: 500, priceMax: 1000, category: 'food', description: 'Catch your own rainbow trout and have it cooked fresh at a hill-station fish farm.', groupFriendly: true, bookingRequired: true, themes: ['food','nature'] },
      { id: 'mn05', name: 'Himalayan Home Meal', location: 'Local Himachali Home', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'food', description: 'Siddu (steamed wheat bread), dham curry, and sepu vadi by a Himachali family.', budgetFriendly: true, groupFriendly: true, themes: ['culture','food'] },
      { id: 'mn06', name: 'Apple Orchard Picnic', location: 'Prini Apple Orchards', durationMinutes: 90, priceMin: 100, priceMax: 300, category: 'food', description: "Wander Manali's famous apple orchards in season, pick fruit, and picnic under the trees.", budgetFriendly: true, groupFriendly: true, themes: ['nature','relax'] },
      { id: 'mn07', name: 'Tibetan Kitchen Lunch', location: 'Tibetan Enclave', durationMinutes: 60, priceMin: 200, priceMax: 500, category: 'food', description: 'Momos, thukpa noodle soup, and butter tea at a Tibetan refugee restaurant.', budgetFriendly: true, themes: ['culture','food'] },
      { id: 'mn08', name: 'Old Manali Cafe with Valley View', location: 'Cafe Himalaya, Old Manali', durationMinutes: 75, priceMin: 350, priceMax: 700, category: 'food', description: "An afternoon at Old Manali's most scenic cafe, overlooking the entire Kullu valley.", themes: ['relax','arrival'] },
      { id: 'mn09', name: 'Jibhi Valley Dhaba Stop', location: 'Jibhi Dhaba', durationMinutes: 90, priceMin: 200, priceMax: 450, category: 'food', description: 'Road-trip lunch at a tiny dhaba in Jibhi valley on the way to Jalori Pass.', budgetFriendly: true, themes: ['adventure','explore'] },
    ],
    afternoon: [
      { id: 'ma01', name: 'Village Cultural Walk', location: 'Old Village Quarter', durationMinutes: 120, priceMin: 100, priceMax: 250, category: 'culture', description: 'Walk through an ancient village, meet local artisans, and see traditional wooden temples.', budgetFriendly: true, groupFriendly: true, themes: ['culture'] },
      { id: 'ma02', name: 'Vashist Hot Spring Soak', location: 'Vashist Hot Springs', durationMinutes: 90, priceMin: 50, priceMax: 200, category: 'rest', description: 'Soothe tired muscles in natural sulphurous hot springs in the Vashist village temple complex.', groupFriendly: true, budgetFriendly: true, themes: ['relax','arrival'] },
      { id: 'ma03', name: 'Tandem Paragliding Flight', location: 'Dobhi Launch Point', durationMinutes: 60, priceMin: 2000, priceMax: 3500, category: 'nature', description: 'Soar above the valley on a tandem paragliding flight with sweeping Himalayan vistas.', bookingRequired: true, premium: true, themes: ['adventure'] },
      { id: 'ma04', name: 'Waterfall Trek & Campsite Setup', location: 'Jagatsukh Waterfall', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'nature', description: 'Short afternoon trek to a hidden waterfall, with camping gear set up on return.', budgetFriendly: true, themes: ['adventure','nature'] },
      { id: 'ma05', name: 'Himalayan Folk Museum', location: 'DHAM Museum', durationMinutes: 90, priceMin: 100, priceMax: 200, category: 'culture', description: 'Artefacts of Himachal life - traditional dresses, folk instruments, and mountain tools.', budgetFriendly: true, themes: ['culture'] },
      { id: 'ma06', name: 'Rock Climbing Intro', location: 'Adventure Club, Manali', durationMinutes: 120, priceMin: 800, priceMax: 1500, category: 'nature', description: 'Learn basic rock-climbing on natural boulders with certified instructors.', bookingRequired: true, themes: ['adventure'] },
      { id: 'ma07', name: "Shepherd's Village Visit", location: 'Jogling Village', durationMinutes: 150, priceMin: 100, priceMax: 300, category: 'culture', description: "Tea and conversation with a local family in an off-the-beaten-path shepherd's village.", budgetFriendly: true, themes: ['culture','food'] },
      { id: 'ma08', name: 'Tibetan Monastery Visit', location: 'Tibetan Monastery, Manali', durationMinutes: 90, priceMin: 0, priceMax: 100, category: 'culture', description: 'Explore a working Tibetan Buddhist monastery with prayer wheels, murals, and butter lamps.', budgetFriendly: true, themes: ['culture','relax'] },
      { id: 'ma09', name: 'Old Manali Hippie Market', location: 'Old Manali Market', durationMinutes: 90, priceMin: 200, priceMax: 600, category: 'shopping', description: "Browse hemp clothing, Tibetan jewellery, and Kullu weaves at Old Manali's market.", themes: ['shopping','culture'] },
    ],
    evening: [
      { id: 'me01', name: 'Bonfire & Stargazing', location: 'Campsite', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'rest', description: 'End your day with a crackling bonfire and clear mountain night skies perfect for stargazing.', groupFriendly: true, budgetFriendly: true, themes: ['relax','arrival','nature'] },
      { id: 'me02', name: 'Local Thali Dinner', location: 'Traditional Guesthouse', durationMinutes: 75, priceMin: 300, priceMax: 600, category: 'food', description: 'A hearty family-style thali with 10+ dishes cooked fresh by a mountain homestead.', groupFriendly: true, budgetFriendly: true, themes: ['arrival','culture','departure'] },
      { id: 'me03', name: 'Artisans & Handicraft Bazaar', location: 'Bazaar Street', durationMinutes: 90, priceMin: 100, priceMax: 300, category: 'shopping', description: 'Browse handwoven shawls, wooden crafts, and local spice blends at a mountain bazaar.', budgetFriendly: true, themes: ['shopping','culture'] },
      { id: 'me04', name: 'Sunset at Hadimba Temple', location: 'Hadimba Devi Temple', durationMinutes: 60, priceMin: 0, priceMax: 50, category: 'culture', description: "Watch golden light fall on the 16th-century pagoda temple set in towering cedar forest.", budgetFriendly: true, themes: ['culture','relax','arrival'] },
      { id: 'me05', name: 'Rooftop Dinner with Valley Views', location: 'Old Manali Rooftop', durationMinutes: 90, priceMin: 500, priceMax: 1200, category: 'food', description: 'Pasta, continental, and local dishes on a candlelit rooftop with Himalayan views.', premium: true, themes: ['explore','relax'] },
      { id: 'me06', name: 'Live Music at Mountain Cafe', location: 'Johnson Cafe', durationMinutes: 120, priceMin: 300, priceMax: 700, category: 'nightlife', description: 'Acoustic sets and local bands play nightly at this beloved Old Manali institution.', groupFriendly: true, themes: ['explore','adventure'] },
      { id: 'me07', name: 'Full Moon Meadow Trek', location: 'Kullu Valley Meadow', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'nature', description: 'A guided evening trek by moonlight through meadows and into the quiet forest.', bookingRequired: true, themes: ['adventure','nature'] },
      { id: 'me08', name: 'Tibetan Cultural Evening', location: 'Tibetan Community Hall', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'culture', description: 'Thangka painting demonstration, butter lamp ceremony, and dharma talk.', themes: ['culture'] },
    ],
  },

  heritage: {
    morning: [
      { id: 'hm01', name: 'Fort & Palace Sunrise Tour', location: 'Historic Fort', durationMinutes: 150, priceMin: 400, priceMax: 900, category: 'culture', description: 'Explore the iconic fort at golden hour before crowds arrive, with an expert local guide.', bookingRequired: true, themes: ['explore','culture'] },
      { id: 'hm02', name: 'Guided Temple Walk', location: 'Old City Temples', durationMinutes: 120, priceMin: 100, priceMax: 300, category: 'culture', description: 'Visit ancient temples with intricate carvings, learning mythology and local lore.', budgetFriendly: true, themes: ['culture'] },
      { id: 'hm03', name: 'Step Well & Heritage Walk', location: 'City Heritage Quarter', durationMinutes: 100, priceMin: 150, priceMax: 350, category: 'culture', description: 'Discover ornate stepwells and havelis on a guided heritage walk through the old city.', budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'hm04', name: 'Sunrise Camel Safari', location: 'Desert Edge', durationMinutes: 120, priceMin: 800, priceMax: 1500, category: 'nature', description: 'Ride a camel into the sand dunes at dawn, watching the desert turn gold.', bookingRequired: true, groupFriendly: true, themes: ['adventure','nature'] },
      { id: 'hm05', name: 'Blue City Walking Tour', location: 'Old City Lanes', durationMinutes: 150, priceMin: 200, priceMax: 500, category: 'culture', description: "Walk the famous colour-coded old-city neighbourhoods with a heritage storyteller guide.", budgetFriendly: true, themes: ['explore','culture'] },
      { id: 'hm06', name: 'Havelis & Frescoes Tour', location: 'Painted Haveli District', durationMinutes: 120, priceMin: 150, priceMax: 400, category: 'culture', description: 'Visit century-old merchant mansions covered in elaborate fresco paintings.', budgetFriendly: true, themes: ['culture'] },
      { id: 'hm07', name: 'Jaipur Gem Stone Workshop', location: 'Johari Bazaar', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'culture', description: 'Watch master gem-cutters at work and learn to identify precious stones.', themes: ['culture','shopping'] },
      { id: 'hm08', name: 'Cycle Rickshaw Heritage Circuit', location: 'Old City', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'culture', description: 'An atmospheric rickshaw ride through the narrowest lanes of the walled old city.', budgetFriendly: true, themes: ['culture','arrival'] },
      { id: 'hm09', name: 'Sunrise Hot Air Balloon', location: 'Fort Outskirts', durationMinutes: 90, priceMin: 6000, priceMax: 12000, category: 'nature', description: "Drift above forts and desert at sunrise in a hot air balloon - a truly spectacular experience.", bookingRequired: true, premium: true, themes: ['adventure','explore'] },
      { id: 'hm10', name: 'Blue Pottery Village Visit', location: 'Blue Pottery Village', durationMinutes: 90, priceMin: 100, priceMax: 300, category: 'culture', description: "Watch Jaipur's famous blue-pottery artisans at work and try your hand at the craft.", budgetFriendly: true, themes: ['culture','food'] },
    ],
    midday: [
      { id: 'hn01', name: 'Traditional Thali Lunch', location: 'Heritage Haveli Restaurant', durationMinutes: 75, priceMin: 350, priceMax: 700, category: 'food', description: 'A lavish thali with 15 dishes served in a restored haveli courtyard.', groupFriendly: true, themes: ['culture','explore'] },
      { id: 'hn02', name: 'Street Food Trail', location: 'Old City Bazaar', durationMinutes: 90, priceMin: 150, priceMax: 350, category: 'food', description: 'Taste kachori, samosa, lassi, and regional sweets on a guided street food walk.', budgetFriendly: true, groupFriendly: true, themes: ['food','culture'] },
      { id: 'hn03', name: 'Rooftop Restaurant with Fort View', location: 'Rooftop Cafe', durationMinutes: 75, priceMin: 600, priceMax: 1200, category: 'food', description: 'Dine on rooftop with sweeping fort views while enjoying Rajasthani curries.', premium: true, themes: ['explore','relax'] },
      { id: 'hn04', name: 'Dal Baati Churma Lunch', location: 'Village Dhaba', durationMinutes: 60, priceMin: 200, priceMax: 400, category: 'food', description: "Rajasthan's iconic meal - round wheat breads roasted over fire, served with five lentil curries.", budgetFriendly: true, themes: ['food','culture'] },
      { id: 'hn05', name: 'Heritage Hotel Afternoon Tea', location: 'Heritage Haveli', durationMinutes: 60, priceMin: 400, priceMax: 800, category: 'food', description: 'Masala chai, mithai, and rose lemonade served on a heritage property lawn.', premium: true, themes: ['relax','arrival'] },
      { id: 'hn06', name: 'Bazaar Spice & Dry Fruit Shopping', location: 'Sardar Market', durationMinutes: 75, priceMin: 100, priceMax: 400, category: 'shopping', description: 'Load up on saffron, dried rose petals, Rajasthani masalas, and local sweets.', budgetFriendly: true, groupFriendly: true, themes: ['shopping','culture'] },
      { id: 'hn07', name: 'Lakeside Cafe Lunch', location: 'Lake Palace Road', durationMinutes: 75, priceMin: 500, priceMax: 1100, category: 'food', description: 'Lunch by the lake with views of white marble palaces reflected in still water.', themes: ['relax','explore'] },
    ],
    afternoon: [
      { id: 'ha01', name: 'Museum & Art Gallery', location: 'City Museum', durationMinutes: 120, priceMin: 100, priceMax: 250, category: 'culture', description: 'Explore royal artefacts, miniature paintings, and weapons from centuries past.', budgetFriendly: true, themes: ['culture'] },
      { id: 'ha02', name: 'Artisan Bazaar Shopping', location: 'Handicraft Market', durationMinutes: 120, priceMin: 200, priceMax: 800, category: 'shopping', description: 'Hunt for block-print textiles, blue pottery, leatherwork, and jewellery at artisan stalls.', groupFriendly: true, themes: ['shopping','culture'] },
      { id: 'ha03', name: 'Camel or Horse Ride', location: 'Palace Grounds', durationMinutes: 60, priceMin: 500, priceMax: 1000, category: 'culture', description: 'Ride a decorated camel or horse around the palace grounds with a local mahout.', bookingRequired: true, premium: true, themes: ['adventure','culture'] },
      { id: 'ha04', name: 'Tie-Dye & Block Printing Workshop', location: 'Craft Workshop', durationMinutes: 120, priceMin: 400, priceMax: 800, category: 'culture', description: 'Create your own block-print fabric using traditional Rajasthani patterns and natural dyes.', bookingRequired: true, groupFriendly: true, themes: ['culture','food'] },
      { id: 'ha05', name: 'Royal Lake Boat Ride', location: 'Pichola Lake', durationMinutes: 60, priceMin: 200, priceMax: 600, category: 'nature', description: 'Row or motor-boat ride across a royal lake to islands with temple ruins.', groupFriendly: true, themes: ['relax','explore'] },
      { id: 'ha06', name: 'Elephant Conservation Centre', location: 'Elephant Village', durationMinutes: 120, priceMin: 1500, priceMax: 2500, category: 'nature', description: 'Ethical elephant interaction - feed, bathe, and learn about rescue elephants.', bookingRequired: true, groupFriendly: true, themes: ['nature','culture'] },
      { id: 'ha07', name: 'Cooking Class: Rajasthani Cuisine', location: 'Heritage Kitchen', durationMinutes: 150, priceMin: 1200, priceMax: 2000, category: 'food', description: 'Learn to cook gatte ki sabji, laal maas, and ghevar with a royal family cook.', bookingRequired: true, premium: true, themes: ['food','culture'] },
      { id: 'ha08', name: 'Puppet Show & Folk Arts Village', location: 'Cultural Village', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'culture', description: 'Traditional Rajasthani puppetry (kathputli) and folk art demonstrations.', groupFriendly: true, budgetFriendly: true, themes: ['culture'] },
    ],
    evening: [
      { id: 'he01', name: 'Cultural Dance Show', location: 'Open Air Amphitheatre', durationMinutes: 90, priceMin: 400, priceMax: 900, category: 'culture', description: 'Watch a vibrant folk dance performance - Ghoomar, Kalbelia, or Chari dance.', bookingRequired: true, groupFriendly: true, themes: ['culture','explore'] },
      { id: 'he02', name: 'Sunset at Heritage Viewpoint', location: 'Hilltop Viewpoint', durationMinutes: 90, priceMin: 0, priceMax: 50, category: 'nature', description: "Walk up to the city's famous viewpoint and watch the fort glow amber at sunset.", budgetFriendly: true, themes: ['relax','arrival','departure'] },
      { id: 'he03', name: 'Heritage Hotel Dinner', location: 'Palace Hotel', durationMinutes: 90, priceMin: 1200, priceMax: 2500, category: 'food', description: 'Dine in a converted royal palace with live sitar music and Rajput cuisine.', premium: true, bookingRequired: true, themes: ['explore','food'] },
      { id: 'he04', name: 'Desert Sand Dune Sunset', location: 'Sam Sand Dunes', durationMinutes: 120, priceMin: 400, priceMax: 900, category: 'nature', description: "Watch the Rajasthan sunset over golden sand dunes with folk musicians by the fire.", groupFriendly: true, themes: ['nature','adventure'] },
      { id: 'he05', name: 'Aarti at the Lake Ghat', location: 'River/Lake Ghat', durationMinutes: 60, priceMin: 0, priceMax: 50, category: 'culture', description: 'Witness the evening fire-lamp ceremony at a sacred ghat with priests and devotees.', budgetFriendly: true, themes: ['culture','arrival','departure'] },
      { id: 'he06', name: 'Night Heritage Walk', location: 'Lit Old City', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'culture', description: 'Guided nocturnal walk through the illuminated old city - forts, temples, and bazaar lanes.', budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'he07', name: 'Rooftop Sundowner', location: 'Fort-view Terrace Bar', durationMinutes: 90, priceMin: 500, priceMax: 1200, category: 'nightlife', description: 'Cocktails and local beer on a rooftop terrace as the fort turns red with dusk.', premium: true, themes: ['relax','explore','arrival'] },
      { id: 'he08', name: 'Open-air Food Market', location: 'Evening Bazaar', durationMinutes: 90, priceMin: 150, priceMax: 400, category: 'food', description: 'Graze through an evening food market - fresh mirchi vada, jalebi, and kulfi.', budgetFriendly: true, groupFriendly: true, themes: ['food','shopping','departure'] },
    ],
  },

  backwater: {
    morning: [
      { id: 'kwm01', name: 'Houseboat Canal Cruise', location: 'Backwater Jetty', durationMinutes: 180, priceMin: 800, priceMax: 1800, category: 'nature', description: 'Glide through narrow canals on a traditional kettuvallam houseboat watching village life.', bookingRequired: true, groupFriendly: true, themes: ['explore','nature'] },
      { id: 'kwm02', name: 'Village Canoe Ride', location: 'Paddy Field Waterway', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'nature', description: 'Paddle through serpentine backwater channels fringed with paddy fields and palms.', budgetFriendly: true, themes: ['nature','relax'] },
      { id: 'kwm03', name: 'Bird Sanctuary Walk', location: 'Kumarakom Bird Sanctuary', durationMinutes: 120, priceMin: 150, priceMax: 350, category: 'nature', description: 'Spot over 60 species of migratory and local birds in a pristine wetland.', budgetFriendly: true, themes: ['nature'] },
      { id: 'kwm04', name: 'Munroe Island Village Tour', location: 'Munroe Island', durationMinutes: 150, priceMin: 400, priceMax: 800, category: 'culture', description: "Explore the archipelago's islands by boat, visiting churches and toddy shops.", groupFriendly: true, themes: ['culture','explore'] },
      { id: 'kwm05', name: 'Early Morning Fishing with Locals', location: 'Village Jetty', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'nature', description: 'Join village fishermen on traditional canoes hauling nets in the early morning mist.', budgetFriendly: true, themes: ['culture','nature'] },
      { id: 'kwm06', name: 'Periyar Lake Boat Safari', location: 'Thekkady', durationMinutes: 180, priceMin: 600, priceMax: 1200, category: 'nature', description: 'Morning boat safari on Periyar Lake to spot elephants, bison, and deer on the banks.', bookingRequired: true, groupFriendly: true, themes: ['adventure','nature'] },
      { id: 'kwm07', name: 'Fort Kochi Heritage Walk', location: 'Fort Kochi', durationMinutes: 150, priceMin: 100, priceMax: 300, category: 'culture', description: 'Chinese fishing nets, Jew Town, Dutch Palace, and St. Francis Church on a morning walk.', budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'kwm08', name: 'Riverside Yoga & Meditation', location: 'Alappuzha Retreat', durationMinutes: 90, priceMin: 500, priceMax: 1000, category: 'rest', description: 'Morning yoga by the backwaters with a certified teacher at a dedicated wellness resort.', themes: ['relax','arrival'] },
      { id: 'kwm09', name: 'Mattancherry Spice Souk Walk', location: 'Mattancherry, Kochi', durationMinutes: 90, priceMin: 0, priceMax: 150, category: 'culture', description: "Kerala's spice trade in action - pepper, cardamom, and ginger warehouses open to visitors.", budgetFriendly: true, themes: ['culture','food'] },
    ],
    midday: [
      { id: 'kwn01', name: 'Backwater Seafood Lunch', location: 'Houseboat Kitchen', durationMinutes: 75, priceMin: 500, priceMax: 900, category: 'food', description: 'Freshly cooked Kerala-style fish curry, appam, and coconut chutney served onboard.', budgetFriendly: true, themes: ['nature','explore'] },
      { id: 'kwn02', name: 'Village Home Banana Leaf Meal', location: 'Local Family Home', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'food', description: 'Share a traditional banana-leaf sadhya cooked by a local Kerala family.', groupFriendly: true, budgetFriendly: true, themes: ['culture','food'] },
      { id: 'kwn03', name: 'Kerala Sadhya Thali', location: 'Temple Festival Ground', durationMinutes: 90, priceMin: 100, priceMax: 300, category: 'food', description: "A traditional 26-dish banana-leaf sadhya - the definitive Kerala meal.", budgetFriendly: true, groupFriendly: true, themes: ['culture','food'] },
      { id: 'kwn04', name: 'Seafood Lunch at Fort Kochi', location: 'Kashi Art Cafe', durationMinutes: 75, priceMin: 500, priceMax: 1000, category: 'food', description: "Grilled Kerala prawn, fish tacos, and fresh lime soda at Fort Kochi's bohemian cafe.", themes: ['culture','food'] },
      { id: 'kwn05', name: 'Coconut Toddy with Tapioca', location: 'Toddy Shop by the Water', durationMinutes: 60, priceMin: 150, priceMax: 350, category: 'food', description: "Fermented coconut toddy and tapioca with fish curry - a true Kerala worker's lunch.", budgetFriendly: true, themes: ['food','culture'] },
      { id: 'kwn06', name: 'Cooking Class: Kerala Curries', location: 'Alappuzha Home Kitchen', durationMinutes: 150, priceMin: 1000, priceMax: 1800, category: 'food', description: 'Learn to make fish moilee, avial, and puttu with a grandmotherly Kerala cook.', bookingRequired: true, themes: ['food','culture'] },
    ],
    afternoon: [
      { id: 'kwa01', name: 'Spice Garden Tour', location: 'Inland Spice Estate', durationMinutes: 90, priceMin: 250, priceMax: 500, category: 'culture', description: 'Walk a working spice estate learning about cardamom, pepper, cinnamon, and turmeric.', groupFriendly: true, themes: ['culture','nature'] },
      { id: 'kwa02', name: 'Ayurvedic Spa Treatment', location: 'Riverside Ayurveda Centre', durationMinutes: 90, priceMin: 1200, priceMax: 2500, category: 'rest', description: 'Enjoy a traditional Ayurvedic Abhyanga massage using warm herbal oils.', premium: true, bookingRequired: true, themes: ['relax'] },
      { id: 'kwa03', name: 'Coir Weaving Workshop', location: 'Village Coir Factory', durationMinutes: 60, priceMin: 100, priceMax: 200, category: 'culture', description: 'Learn traditional coir rope and mat weaving from local artisans.', budgetFriendly: true, themes: ['culture'] },
      { id: 'kwa04', name: 'Kalaripayattu Martial Arts Show', location: 'Kalari Centre', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'culture', description: "Watch a live performance of Kerala's ancient martial art - acrobatic sword-and-shield combat.", bookingRequired: true, groupFriendly: true, themes: ['culture','adventure'] },
      { id: 'kwa05', name: 'Vembanad Lake Cycling', location: 'Kumarakom Bund Road', durationMinutes: 120, priceMin: 200, priceMax: 400, category: 'nature', description: 'Cycle along the Vembanad Lake bund watching fishermen, rice paddies, and water birds.', budgetFriendly: true, themes: ['nature','explore'] },
      { id: 'kwa06', name: 'Snake Boat Tour', location: 'Champakkulam', durationMinutes: 90, priceMin: 400, priceMax: 800, category: 'culture', description: 'Ride a traditional Chundan vallam (snake boat) on the backwaters - a living piece of history.', bookingRequired: true, groupFriendly: true, themes: ['culture','adventure'] },
      { id: 'kwa07', name: 'Wetland Nature Walk', location: 'Vembanad Wetland', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'nature', description: 'Expert-guided walk through wetlands and paddy fields spotting migratory birds.', themes: ['nature'] },
      { id: 'kwa08', name: 'Jewish Synagogue & Spice Market', location: 'Jew Town, Kochi', durationMinutes: 90, priceMin: 100, priceMax: 250, category: 'culture', description: "Visit India's oldest synagogue and the surrounding spice trade quarter.", budgetFriendly: true, themes: ['culture'] },
    ],
    evening: [
      { id: 'kwe01', name: 'Sunset Canoe through Palms', location: 'Village Jetty', durationMinutes: 90, priceMin: 400, priceMax: 800, category: 'nature', description: 'Drift through tranquil backwaters at golden hour as the sky turns crimson.', groupFriendly: true, themes: ['relax','arrival','departure'] },
      { id: 'kwe02', name: 'Kerala Kathakali Performance', location: 'Cultural Centre', durationMinutes: 90, priceMin: 350, priceMax: 700, category: 'culture', description: 'Watch the ancient Kathakali dance-drama with elaborate costumes and facial expressions.', bookingRequired: true, themes: ['culture','explore'] },
      { id: 'kwe03', name: 'Backwater Dinner Cruise', location: 'Jetty Boarding Point', durationMinutes: 120, priceMin: 1500, priceMax: 3000, category: 'food', description: 'Dine on a private dinner cruise through moonlit backwaters.', premium: true, bookingRequired: true, themes: ['explore','food'] },
      { id: 'kwe04', name: 'Chinese Fishing Net Sunset', location: 'Fort Kochi Shoreline', durationMinutes: 60, priceMin: 0, priceMax: 50, category: 'nature', description: "Watch the iconic Chinese fishing nets operate at sunset - one of Kerala's most iconic sights.", budgetFriendly: true, themes: ['arrival','departure','relax'] },
      { id: 'kwe05', name: 'Contemporary Art Walk', location: 'Aspinwall House & Venues', durationMinutes: 120, priceMin: 100, priceMax: 300, category: 'culture', description: "Immersive art installations in Kochi's colonial warehouses.", themes: ['culture'] },
      { id: 'kwe06', name: 'Toddy Shop Sundowner', location: 'Alappuzha Waterfront', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'food', description: "Watch the sun set over Alappuzha's famous beach while drinking toddy with fried fish.", budgetFriendly: true, themes: ['relax','food'] },
      { id: 'kwe07', name: 'Mohiniyattam Dance Performance', location: 'Sangeet Natak Academy', durationMinutes: 75, priceMin: 300, priceMax: 600, category: 'culture', description: "Attend a performance of Kerala's graceful classical dance form.", bookingRequired: true, themes: ['culture'] },
      { id: 'kwe08', name: 'Houseboat Sundowner', location: 'Your Houseboat', durationMinutes: 90, priceMin: 500, priceMax: 1200, category: 'rest', description: 'Drinks on deck as your houseboat moors for the night, watching fireflies over the water.', themes: ['relax','nature'] },
    ],
  },

  city: {
    morning: [
      { id: 'cm01', name: 'Heritage Neighbourhood Walk', location: 'Old City Quarter', durationMinutes: 120, priceMin: 0, priceMax: 200, category: 'culture', description: "Explore the city's oldest lanes, colonial architecture, and local market life.", budgetFriendly: true, themes: ['explore','culture'] },
      { id: 'cm02', name: 'City Art Museum', location: 'City Art Gallery', durationMinutes: 90, priceMin: 100, priceMax: 250, category: 'culture', description: "Discover local and national artists at the city's premier art gallery.", budgetFriendly: true, themes: ['culture'] },
      { id: 'cm03', name: 'Local Breakfast Food Crawl', location: 'Street Food Hub', durationMinutes: 90, priceMin: 150, priceMax: 400, category: 'food', description: 'Sample regional breakfast specialities - idli, vada, pav bhaji, or chole kulche - on foot.', budgetFriendly: true, groupFriendly: true, themes: ['food','arrival'] },
      { id: 'cm04', name: 'Dawn Cycle Tour', location: 'City Greenway', durationMinutes: 90, priceMin: 300, priceMax: 600, category: 'nature', description: "Cycle through the city's parks and riverside promenades before traffic builds.", budgetFriendly: true, themes: ['explore','nature'] },
      { id: 'cm05', name: 'Sunrise at the Riverfront Ghat', location: 'City Ghat', durationMinutes: 60, priceMin: 0, priceMax: 50, category: 'nature', description: "Watch the city wake up along the riverfront at dawn - bathers, rowers, and morning prayers.", budgetFriendly: true, themes: ['arrival','relax'] },
      { id: 'cm06', name: 'Bollywood Film Studio Tour', location: 'Film City', durationMinutes: 150, priceMin: 600, priceMax: 1200, category: 'culture', description: 'Behind-the-scenes tour of a working Bollywood studio with costume and set exhibitions.', bookingRequired: true, groupFriendly: true, themes: ['culture','explore'] },
      { id: 'cm07', name: 'Yoga at City Ashram', location: 'City Ashram', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'rest', description: 'Morning yoga and pranayama session at a certified urban ashram.', budgetFriendly: true, themes: ['relax','arrival'] },
      { id: 'cm08', name: 'City Photography Walk', location: 'Mixed Neighbourhood', durationMinutes: 120, priceMin: 300, priceMax: 700, category: 'culture', description: 'Guided walk with a photo-journalist through street markets, temples, and backstreets.', themes: ['explore','culture'] },
      { id: 'cm09', name: 'City Edge National Park Safari', location: 'City Edge National Park', durationMinutes: 150, priceMin: 600, priceMax: 1200, category: 'nature', description: 'Morning jeep safari to spot leopard, deer, and birds within city limits.', bookingRequired: true, themes: ['nature','adventure'] },
    ],
    midday: [
      { id: 'cnn01', name: 'Trendy Cafe Lunch', location: 'Design District Cafe', durationMinutes: 75, priceMin: 500, priceMax: 1000, category: 'food', description: 'Enjoy contemporary Indian small plates and specialty coffee at a design-forward cafe.', premium: true, themes: ['explore','relax'] },
      { id: 'cnn02', name: 'Street Food Lunch at Market', location: 'Central Market', durationMinutes: 60, priceMin: 150, priceMax: 350, category: 'food', description: 'A quick, delicious lunch of regional street favourites at a busy urban market.', budgetFriendly: true, themes: ['food','arrival'] },
      { id: 'cnn03', name: 'Legendary Biryani Lunch', location: 'Storied Biryani Restaurant', durationMinutes: 75, priceMin: 300, priceMax: 700, category: 'food', description: "A pilgrimage to the city's most storied biryani restaurant - packed since 1950.", budgetFriendly: true, groupFriendly: true, themes: ['food','culture'] },
      { id: 'cnn04', name: 'Mall & Local Brand Shopping', location: 'Premium Mall', durationMinutes: 90, priceMin: 0, priceMax: 500, category: 'shopping', description: 'Upscale shopping for Indian and international brands with food court break.', groupFriendly: true, themes: ['shopping'] },
      { id: 'cnn05', name: 'Workers Canteen Thali', location: 'City Canteen', durationMinutes: 45, priceMin: 80, priceMax: 200, category: 'food', description: "A generous thali at a no-frills city canteen - eat like a local for under 150.", budgetFriendly: true, themes: ['food','explore'] },
      { id: 'cnn06', name: 'Irani Cafe Experience', location: 'Old Irani Cafe', durationMinutes: 60, priceMin: 100, priceMax: 300, category: 'food', description: 'Sip chai and eat bun maska at a 100-year-old Persian-style cafe - a city institution.', budgetFriendly: true, themes: ['culture','food','relax'] },
      { id: 'cnn07', name: 'South Indian Tiffin Lunch', location: 'Udupi Restaurant', durationMinutes: 60, priceMin: 100, priceMax: 300, category: 'food', description: "Unlimited sambar, rasam, and rice at a legendary South Indian tiffin house.", budgetFriendly: true, groupFriendly: true, themes: ['food'] },
    ],
    afternoon: [
      { id: 'ca01', name: 'National Museum Deep Dive', location: 'National/State Museum', durationMinutes: 120, priceMin: 50, priceMax: 150, category: 'culture', description: "Spend the afternoon in the city's most important museum - art, history, or science.", budgetFriendly: true, themes: ['culture'] },
      { id: 'ca02', name: 'Shopping Mall & Local Brands', location: 'Central Mall', durationMinutes: 120, priceMin: 0, priceMax: 500, category: 'shopping', description: 'Browse local designer boutiques, Indian brands, and popular street-fashion stores.', groupFriendly: true, themes: ['shopping'] },
      { id: 'ca03', name: 'Urban Street Art Walk', location: 'Art District', durationMinutes: 90, priceMin: 0, priceMax: 100, category: 'culture', description: "Explore the city's vibrant street mural scene in the artist quarter.", budgetFriendly: true, themes: ['culture','explore'] },
      { id: 'ca04', name: 'Bollywood Dance Class', location: 'Dance Studio', durationMinutes: 90, priceMin: 500, priceMax: 1000, category: 'culture', description: 'One-hour Bollywood dance lesson for all levels - garba, bhangra, and filmy moves.', bookingRequired: true, groupFriendly: true, themes: ['culture','adventure'] },
      { id: 'ca05', name: 'Craft Beer Brewery Tour', location: 'Microbrewery', durationMinutes: 90, priceMin: 600, priceMax: 1200, category: 'food', description: 'Tour a craft brewery and taste seasonal IPAs, stouts, and wheat beers.', premium: true, themes: ['food','explore'] },
      { id: 'ca06', name: 'Pottery Quarter Visit', location: 'Pottery Village', durationMinutes: 120, priceMin: 200, priceMax: 500, category: 'culture', description: 'Traditional potters at work - watch and buy direct from the source.', budgetFriendly: true, themes: ['culture'] },
      { id: 'ca07', name: 'City Fort & Ruins Walk', location: 'City Fort', durationMinutes: 120, priceMin: 100, priceMax: 300, category: 'culture', description: "Roam an old fort or ruins on the city's edge - often empty and full of history.", budgetFriendly: true, themes: ['culture','nature'] },
    ],
    evening: [
      { id: 'ce01', name: 'Rooftop Bar & City Views', location: 'Skybar, City Centre', durationMinutes: 120, priceMin: 800, priceMax: 2000, category: 'nightlife', description: 'Cocktails with panoramic city views from a chic rooftop lounge.', premium: true, bookingRequired: true, themes: ['arrival','explore','relax'] },
      { id: 'ce02', name: 'Live Music Venue', location: 'Jazz/Indie Bar', durationMinutes: 150, priceMin: 400, priceMax: 900, category: 'nightlife', description: "Catch a live set at one of the city's best independent music venues.", groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'ce03', name: 'Fine Dining Tasting Menu', location: 'Award-winning Restaurant', durationMinutes: 120, priceMin: 1500, priceMax: 4000, category: 'food', description: 'Tasting menu dinner at a celebrated restaurant showcasing modern Indian cuisine.', premium: true, bookingRequired: true, themes: ['food','explore'] },
      { id: 'ce04', name: 'Street Food Night Walk', location: 'Night Food Street', durationMinutes: 90, priceMin: 200, priceMax: 500, category: 'food', description: "Join locals at the city's famous night street food strip.", budgetFriendly: true, groupFriendly: true, themes: ['food','arrival','departure'] },
      { id: 'ce05', name: 'Classical Music or Theatre', location: 'City Auditorium', durationMinutes: 120, priceMin: 300, priceMax: 900, category: 'culture', description: 'Evening at a performance of Indian classical music, theatre, or a stand-up show.', bookingRequired: true, themes: ['culture'] },
      { id: 'ce06', name: 'Comedy Club Night', location: 'Comedy Venue', durationMinutes: 120, priceMin: 400, priceMax: 800, category: 'nightlife', description: "Local stand-up comics perform at the city's leading comedy venue.", bookingRequired: true, groupFriendly: true, themes: ['adventure','explore'] },
      { id: 'ce07', name: 'Night Market & Chai', location: 'City Night Market', durationMinutes: 90, priceMin: 100, priceMax: 400, category: 'shopping', description: 'Wander evening stalls for local snacks, clothes, and trinkets with a cup of cutting chai.', budgetFriendly: true, groupFriendly: true, themes: ['shopping','arrival','departure'] },
      { id: 'ce08', name: 'Temple Aarti & Devotional Walk', location: 'City Temple Complex', durationMinutes: 60, priceMin: 0, priceMax: 100, category: 'culture', description: 'Join evening prayers and witness the aarti ceremony at a major city temple.', budgetFriendly: true, themes: ['culture','relax'] },
    ],
  },
};

/** Pick a random-ish item from array using a seeded number */
export function seededPick<T>(arr: T[], seed: number, offset: number = 0): T {
  return arr[(seed + offset) % arr.length];
}
